// <auto-generated />
namespace Library.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BookingChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BookingChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201906291800210_BookingChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
